import { type Metadata } from "next";
import { type PropsWithChildren } from "react";
import { AuthProvider } from "@/components";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MainLayout({ children }: PropsWithChildren) {
  return <AuthProvider>{children}</AuthProvider>;
}
